apiVersion: v1
name: nginx
version: "0.1.0"
kubeVersion: "1.10.3"
description: A Helm chart for Kubernetes Nginx
keywords:
  - nginx
#home: 
#sources:
#  - 
maintainers: 
  - name: Sandeep Lamba
    email: sandeep.lamba@grandparade.co.uk
    url: 
engine: gotpl
#icon: A URL to an SVG or PNG image to be used as an icon (optional).
appVersion: "1.0"
deprecated: false
tillerVersion: "2.9.1"
